export const locations = [
  // NORTH LUZON (1)
  {
    code: "ALA",
    city: "Alaminos",
    region: "Ilocos Region",
    regionCode: "ILC",
    tag: 1,
  },
  {
    code: "BTC",
    city: "Batac",
    region: "Ilocos Region",
    regionCode: "ILC",
    tag: 1,
  },
  {
    code: "BAG",
    city: "Baguio",
    region: "Cordillera Administrative Region",
    regionCode: "CAR",
    tag: 1,
  },
  {
    code: "CDN",
    city: "Candon",
    region: "Ilocos Region",
    regionCode: "ILC",
    tag: 1,
  },
  {
    code: "CAU",
    city: "Cauayan",
    region: "Cagayan Valley",
    regionCode: "CAV",
    tag: 1,
  },
  {
    code: "ILA",
    city: "Ilagan",
    region: "Cagayan Valley",
    regionCode: "CAV",
    tag: 1,
  },
  {
    code: "LAO",
    city: "Laoag",
    region: "Ilocos Region",
    regionCode: "ILC",
    tag: 1,
  },
  {
    code: "MZO",
    city: "Munoz",
    region: "Central Luzon",
    regionCode: "CLZ",
    tag: 2,
  },
  {
    code: "SNT",
    city: "Santiago",
    region: "Cagayan Valley",
    regionCode: "CAV",
    tag: 1,
  },
  {
    code: "TUG",
    city: "Tuguegarao",
    region: "Cagayan Valley",
    regionCode: "CAV",
    tag: 1,
  },
  {
    code: "URD",
    city: "Urdaneta",
    region: "Ilocos Region",
    regionCode: "ILC",
    tag: 1,
  },
  {
    code: "VIG",
    city: "Vigan",
    region: "Ilocos Region",
    regionCode: "ILC",
    tag: 1,
  },
  {
    code: "TAB",
    city: "Tabuk",
    region: "Cordillera Administrative Region",
    regionCode: "CAR",
    tag: 1,
  },

  // CENTRAL LUZON / NCR (2)
  {
    code: "ANG",
    city: "Angeles City",
    region: "Central Luzon",
    regionCode: "CLZ",
    tag: 2,
  },
  {
    code: "BAL",
    city: "Balanga",
    region: "Central Luzon",
    regionCode: "CLZ",
    tag: 2,
  },
  {
    code: "BLW",
    city: "Baliwag",
    region: "Central Luzon",
    regionCode: "CLZ",
    tag: 2,
  },
  {
    code: "CAB",
    city: "Cabanatuan",
    region: "Central Luzon",
    regionCode: "CLZ",
    tag: 2,
  },
  {
    code: "GAP",
    city: "Gapan",
    region: "Central Luzon",
    regionCode: "CLZ",
    tag: 2,
  },
  {
    code: "MAB",
    city: "Mabalacat",
    region: "Central Luzon",
    regionCode: "CLZ",
    tag: 2,
  },
  {
    code: "MOL",
    city: "Malolos",
    region: "Central Luzon",
    regionCode: "CLZ",
    tag: 2,
  },
  {
    code: "MEY",
    city: "Meycauayan",
    region: "Central Luzon",
    regionCode: "CLZ",
    tag: 2,
  },
  {
    code: "OLG",
    city: "Olongapo",
    region: "Central Luzon",
    regionCode: "CLZ",
    tag: 2,
  },
  {
    code: "PLN",
    city: "Palayan",
    region: "Central Luzon",
    regionCode: "CLZ",
    tag: 2,
  },
  {
    code: "SFC",
    city: "San Fernando",
    region: "Central Luzon",
    regionCode: "CLZ",
    tag: 2,
  },
  {
    code: "TAR",
    city: "Tarlac City",
    region: "Central Luzon",
    regionCode: "CLZ",
    tag: 2,
  },

  {
    code: "CAL",
    city: "Caloocan",
    region: "Metro Manila",
    regionCode: "NCR",
    tag: 2,
  },
  {
    code: "LAS",
    city: "Las Pinas",
    region: "Metro Manila",
    regionCode: "NCR",
    tag: 2,
  },
  {
    code: "MAK",
    city: "Makati",
    region: "Metro Manila",
    regionCode: "NCR",
    tag: 2,
  },
  {
    code: "MLB",
    city: "Malabon",
    region: "Metro Manila",
    regionCode: "NCR",
    tag: 2,
  },
  {
    code: "MNL",
    city: "Manila",
    region: "Metro Manila",
    regionCode: "NCR",
    tag: 2,
  },
  {
    code: "MRK",
    city: "Marikina",
    region: "Metro Manila",
    regionCode: "NCR",
    tag: 2,
  },
  {
    code: "MDY",
    city: "Mandaluyong",
    region: "Metro Manila",
    regionCode: "NCR",
    tag: 2,
  },
  {
    code: "MUN",
    city: "Muntinlupa",
    region: "Metro Manila",
    regionCode: "NCR",
    tag: 2,
  },
  {
    code: "NAV",
    city: "Navotas",
    region: "Metro Manila",
    regionCode: "NCR",
    tag: 2,
  },
  {
    code: "PAR",
    city: "Paranaque",
    region: "Metro Manila",
    regionCode: "NCR",
    tag: 2,
  },
  {
    code: "PAS",
    city: "Pasay",
    region: "Metro Manila",
    regionCode: "NCR",
    tag: 2,
  },
  {
    code: "PSG",
    city: "Pasig",
    region: "Metro Manila",
    regionCode: "NCR",
    tag: 2,
  },
  {
    code: "QZN",
    city: "Quezon City",
    region: "Metro Manila",
    regionCode: "NCR",
    tag: 2,
  },
  {
    code: "SJU",
    city: "San Juan",
    region: "Metro Manila",
    regionCode: "NCR",
    tag: 2,
  },
  {
    code: "TAG",
    city: "Taguig",
    region: "Metro Manila",
    regionCode: "NCR",
    tag: 2,
  },
  {
    code: "VAL",
    city: "Valenzuela",
    region: "Metro Manila",
    regionCode: "NCR",
    tag: 2,
  },

  // SOUTHERN LUZON (3)
  {
    code: "ANT",
    city: "Antipolo",
    region: "Calabarzon",
    regionCode: "CAL",
    tag: 3,
  },
  {
    code: "BAC",
    city: "Bacoor",
    region: "Calabarzon",
    regionCode: "CAL",
    tag: 3,
  },
  {
    code: "BTG",
    city: "Batangas City",
    region: "Calabarzon",
    regionCode: "CAL",
    tag: 3,
  },
  {
    code: "CBY",
    city: "Cabuyao",
    region: "Calabarzon",
    regionCode: "CAL",
    tag: 3,
  },
  {
    code: "CLC",
    city: "Calaca",
    region: "Calabarzon",
    regionCode: "CAL",
    tag: 3,
  },
  {
    code: "CLM",
    city: "Calamba",
    region: "Calabarzon",
    regionCode: "CAL",
    tag: 3,
  },
  {
    code: "CVT",
    city: "Cavite City",
    region: "Calabarzon",
    regionCode: "CAL",
    tag: 3,
  },
  {
    code: "DSM",
    city: "Dasmarinas",
    region: "Calabarzon",
    regionCode: "CAL",
    tag: 3,
  },
  {
    code: "IMU",
    city: "Imus",
    region: "Calabarzon",
    regionCode: "CAL",
    tag: 3,
  },
  {
    code: "LIP",
    city: "Lipa",
    region: "Calabarzon",
    regionCode: "CAL",
    tag: 3,
  },
  {
    code: "LUC",
    city: "Lucena",
    region: "Calabarzon",
    regionCode: "CAL",
    tag: 3,
  },
  {
    code: "SRO",
    city: "Santa Rosa",
    region: "Calabarzon",
    regionCode: "CAL",
    tag: 3,
  },
  {
    code: "STM",
    city: "Santo Tomas",
    region: "Calabarzon",
    regionCode: "CAL",
    tag: 3,
  },
  {
    code: "TAY",
    city: "Tayabas",
    region: "Calabarzon",
    regionCode: "CAL",
    tag: 3,
  },
  {
    code: "TGY",
    city: "Tagaytay",
    region: "Calabarzon",
    regionCode: "CAL",
    tag: 3,
  },
  {
    code: "TRC",
    city: "Trece Martires",
    region: "Calabarzon",
    regionCode: "CAL",
    tag: 3,
  },
  {
    code: "SJM",
    city: "San Jose Del Monte",
    region: "Central Luzon",
    regionCode: "CLZ",
    tag: 2,
  },

  {
    code: "IRG",
    city: "Iriga",
    region: "Bicol Region",
    regionCode: "BIC",
    tag: 3,
  },
  {
    code: "LGZ",
    city: "Legazpi",
    region: "Bicol Region",
    regionCode: "BIC",
    tag: 3,
  },
  {
    code: "LIG",
    city: "Ligao",
    region: "Bicol Region",
    regionCode: "BIC",
    tag: 3,
  },
  {
    code: "NGC",
    city: "Naga",
    region: "Bicol Region",
    regionCode: "BIC",
    tag: 3,
  },
  {
    code: "SRG",
    city: "Sorsogon City",
    region: "Bicol Region",
    regionCode: "BIC",
    tag: 3,
  },
  {
    code: "TBC",
    city: "Tabaco",
    region: "Bicol Region",
    regionCode: "BIC",
    tag: 3,
  },
  {
    code: "MSC",
    city: "Masbate City",
    region: "Bicol Region",
    regionCode: "BIC",
    tag: 3,
  },

  // VISAYAS (4)
  {
    code: "BCD",
    city: "Bacolod",
    region: "Western Visayas",
    regionCode: "WVS",
    tag: 4,
  },
  {
    code: "BGO",
    city: "Bago",
    region: "Western Visayas",
    regionCode: "WVS",
    tag: 4,
  },
  {
    code: "CDZ",
    city: "Cadiz",
    region: "Western Visayas",
    regionCode: "WVS",
    tag: 4,
  },
  {
    code: "ESC",
    city: "Escalante",
    region: "Western Visayas",
    regionCode: "WVS",
    tag: 4,
  },
  {
    code: "HIM",
    city: "Himamaylan",
    region: "Western Visayas",
    regionCode: "WVS",
    tag: 4,
  },
  {
    code: "KBL",
    city: "Kabankalan",
    region: "Western Visayas",
    regionCode: "WVS",
    tag: 4,
  },
  {
    code: "LCL",
    city: "La Carlota",
    region: "Western Visayas",
    regionCode: "WVS",
    tag: 4,
  },
  {
    code: "PSI",
    city: "Passi",
    region: "Western Visayas",
    regionCode: "WVS",
    tag: 4,
  },
  {
    code: "ROX",
    city: "Roxas",
    region: "Western Visayas",
    regionCode: "WVS",
    tag: 4,
  },
  {
    code: "SGY",
    city: "Sagay",
    region: "Western Visayas",
    regionCode: "WVS",
    tag: 4,
  },
  {
    code: "SLY",
    city: "Silay",
    region: "Western Visayas",
    regionCode: "WVS",
    tag: 4,
  },
  {
    code: "SPY",
    city: "Sipalay",
    region: "Western Visayas",
    regionCode: "WVS",
    tag: 4,
  },
  {
    code: "VIC",
    city: "Victorias",
    region: "Western Visayas",
    regionCode: "WVS",
    tag: 4,
  },

  {
    code: "BIS",
    city: "Bais",
    region: "Central Visayas",
    regionCode: "CVS",
    tag: 4,
  },
  {
    code: "BGO",
    city: "Bogo",
    region: "Central Visayas",
    regionCode: "CVS",
    tag: 4,
  },
  {
    code: "CAR",
    city: "Carcar",
    region: "Central Visayas",
    regionCode: "CVS",
    tag: 4,
  },
  {
    code: "CEB",
    city: "Cebu City",
    region: "Central Visayas",
    regionCode: "CVS",
    tag: 4,
  },
  {
    code: "DNO",
    city: "Danao",
    region: "Central Visayas",
    regionCode: "CVS",
    tag: 4,
  },
  {
    code: "LAP",
    city: "Lapu-Lapu City",
    region: "Central Visayas",
    regionCode: "CVS",
    tag: 4,
  },
  {
    code: "MDU",
    city: "Mandaue",
    region: "Central Visayas",
    regionCode: "CVS",
    tag: 4,
  },
  {
    code: "TLD",
    city: "Toledo",
    region: "Central Visayas",
    regionCode: "CVS",
    tag: 4,
  },
  {
    code: "TAG",
    city: "Tagbilaran",
    region: "Central Visayas",
    regionCode: "CVS",
    tag: 4,
  },
  {
    code: "TAL",
    city: "Talisay",
    region: "Central Visayas",
    regionCode: "CVS",
    tag: 4,
  },

  {
    code: "BOR",
    city: "Borongan",
    region: "Eastern Visayas",
    regionCode: "EVS",
    tag: 4,
  },
  {
    code: "CAT",
    city: "Catbalogan",
    region: "Eastern Visayas",
    regionCode: "EVS",
    tag: 4,
  },
  {
    code: "CLB",
    city: "Calbayog",
    region: "Eastern Visayas",
    regionCode: "EVS",
    tag: 4,
  },
  {
    code: "ORM",
    city: "Ormoc",
    region: "Eastern Visayas",
    regionCode: "EVS",
    tag: 4,
  },
  {
    code: "TAC",
    city: "Tacloban",
    region: "Eastern Visayas",
    regionCode: "EVS",
    tag: 4,
  },
  {
    code: "BYB",
    city: "Baybay",
    region: "Eastern Visayas",
    regionCode: "EVS",
    tag: 4,
  },

  // MINDANAO (5)
  { code: "BDR", city: "Bayugan", region: "Caraga", regionCode: "CRG", tag: 5 },
  { code: "BIS", city: "Bislig", region: "Caraga", regionCode: "CRG", tag: 5 },
  { code: "BTU", city: "Butuan", region: "Caraga", regionCode: "CRG", tag: 5 },
  {
    code: "CBD",
    city: "Cabadbaran",
    region: "Caraga",
    regionCode: "CRG",
    tag: 5,
  },
  {
    code: "SRG",
    city: "Surigao City",
    region: "Caraga",
    regionCode: "CRG",
    tag: 5,
  },
  { code: "TND", city: "Tandag", region: "Caraga", regionCode: "CRG", tag: 5 },

  {
    code: "ELS",
    city: "El Salvador",
    region: "Northern Mindanao",
    regionCode: "NMD",
    tag: 5,
  },
  {
    code: "GNG",
    city: "Gingoog",
    region: "Northern Mindanao",
    regionCode: "NMD",
    tag: 5,
  },
  {
    code: "ILG",
    city: "Iligan",
    region: "Northern Mindanao",
    regionCode: "NMD",
    tag: 5,
  },
  {
    code: "MAL",
    city: "Malaybalay",
    region: "Northern Mindanao",
    regionCode: "NMD",
    tag: 5,
  },
  {
    code: "ORO",
    city: "Oroquieta",
    region: "Northern Mindanao",
    regionCode: "NMD",
    tag: 5,
  },
  {
    code: "OZM",
    city: "Ozamiz",
    region: "Northern Mindanao",
    regionCode: "NMD",
    tag: 5,
  },
  {
    code: "TNG",
    city: "Tangub",
    region: "Northern Mindanao",
    regionCode: "NMD",
    tag: 5,
  },

  {
    code: "DVO",
    city: "Davao City",
    region: "Davao Region",
    regionCode: "DAV",
    tag: 5,
  },
  {
    code: "DGS",
    city: "Digos",
    region: "Davao Region",
    regionCode: "DAV",
    tag: 5,
  },
  {
    code: "MAT",
    city: "Mati",
    region: "Davao Region",
    regionCode: "DAV",
    tag: 5,
  },
  {
    code: "PBO",
    city: "Panabo",
    region: "Davao Region",
    regionCode: "DAV",
    tag: 5,
  },
  {
    code: "SAM",
    city: "Samal",
    region: "Davao Region",
    regionCode: "DAV",
    tag: 5,
  },
  {
    code: "TAG",
    city: "Tagum",
    region: "Davao Region",
    regionCode: "DAV",
    tag: 5,
  },

  {
    code: "GSC",
    city: "General Santos",
    region: "Region XII",
    regionCode: "SOX",
    tag: 5,
  },
  {
    code: "KDP",
    city: "Kidapawan",
    region: "Region XII",
    regionCode: "SOX",
    tag: 5,
  },
  {
    code: "KOR",
    city: "Koronadal",
    region: "Region XII",
    regionCode: "SOX",
    tag: 5,
  },
  {
    code: "TCR",
    city: "Tacurong",
    region: "Region XII",
    regionCode: "SOX",
    tag: 5,
  },

  {
    code: "DPT",
    city: "Dapitan",
    region: "Zamboanga Peninsula",
    regionCode: "ZAM",
    tag: 5,
  },
  {
    code: "DPL",
    city: "Dipolog",
    region: "Zamboanga Peninsula",
    regionCode: "ZAM",
    tag: 5,
  },
  {
    code: "PGD",
    city: "Pagadian",
    region: "Zamboanga Peninsula",
    regionCode: "ZAM",
    tag: 5,
  },
  {
    code: "ZAM",
    city: "Zamboanga City",
    region: "Zamboanga Peninsula",
    regionCode: "ZAM",
    tag: 5,
  },

  {
    code: "CTB",
    city: "Cotabato City",
    region: "Bangsamoro Autonomous Region in Muslim Mindanao",
    regionCode: "BAR",
    tag: 5,
  },
  {
    code: "LAM",
    city: "Lamitan",
    region: "Bangsamoro Autonomous Region in Muslim Mindanao",
    regionCode: "BAR",
    tag: 5,
  },
  {
    code: "MRW",
    city: "Marawi",
    region: "Bangsamoro Autonomous Region in Muslim Mindanao",
    regionCode: "BAR",
    tag: 5,
  },
];
